language: generic

env:
- TRAVIS_TAG="Deploy-2019.2.0f1" PROJECT_NAME="LeVRnTravisPackageBuild" UNITY_PROJECT_PATH="UnityProject" DEPLOY_UNITYPACKAGE="path set in deploy script"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- chmod a+x ./Scripts/*.sh

install:
- cat /etc/hosts
- ./Scripts/Install.sh

script:
- ./Scripts/Build.sh
- ./Scripts/Run-tests.sh

after_success:
- ./Scripts/Export-unity-package.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true 
